$(document).ready(function(){
  $('.button-link').click(function(event){
    event.preventDefault();
  });
  $('.button-addition').click(function(){
    console.log('追加');
    $('.hidden-url-input-parts').first().addClass('displayed-url-input-parts');
    $('.hidden-url-input-parts').first().removeClass('hidden-url-input-parts');
    $('.hidden-button').first().removeClass('hidden-button');
  });
  $('.button-removal').click(function(){
    let index = $('.button-removal').index(this);
    console.log(index);
    $('.inline-block-input-parts').eq(index).val('');
    $('.inline-block-input-parts').eq(index).addClass('hidden-url-input-parts');
    $('.inline-block-input-parts').eq(index).removeClass('displayed-url-input-parts');
    $('.button-removal').eq(index).addClass('hidden-button');
  });
});
