inherit_from: .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "script/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "node_modules/**/*"
    - "config/puma.rb"
    - ".git/**/*"
    - "spec/**/**"
