services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    stdin_open: true
    tty: true
    build: .
    command: /bin/sh -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/docker_rails
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
      - log-data:/docker_rails/log
  web:
    build: nginx
    volumes:
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
    ports:
      - "80:80"
    depends_on:
      - app
  front:
    build:
      context: ./habit_react/
    volumes:
      - ./habit_react/:/docker_rails/habit_react
    command: 'yarn dev'
    ports:
      - "8080:3000"

volumes:
  db-store:
  public-data:
  tmp-data:
  log-data:
