services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: nginx
    volumes:
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
    ports:
      - "80:80"
    depends_on:
      - app
  front:
    build:
      context: ./habit_react/
    volumes:
      - ./habit_react/:/docker_rails/habit_react
    command: 'yarn dev'
    ports:
      - "8080:80"
  app:
    stdin_open: true
    tty: true
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    depends_on:
      - db
    ports:
      - "3000:80"
    volumes:
      - .:/docker_rails
      - public-data:/docker_rails/public
      - tmp-data:/docker_rails/tmp
      - log-data:/docker_rails/log

volumes:
  db-store:
  public-data:
  tmp-data:
  log-data:
