services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    stdin_open: true
    tty: true
    build: .
    command: /bin/sh -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/docker_rails
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome

  chrome:
    image: seleniarm/standalone-chromium
    platform: linux/amd64
    ports:
      - 4444:4444

volumes:
  db-store:
