version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose -f compose.yml build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f compose.yml up -d
      - run:
          name: db接続を待機
          command: sleep 10
      - run:
          name: データベースのセットアップ
          command: docker-compose -f compose.yml exec web bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: webpackerのコンパイル
          command: docker-compose run web bundle exec rails webpacker:compile
      - run:
          name: rspecの実行
          command: docker-compose run --rm web bundle exec rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose -f compose.yml down
